sudo: required
language: java

services:
  - docker

jdk:
  - openjdk8

env:
  global:
    - DOCKER_CFG=$HOME/.docker
    - DOCKER_REPO="utplsqlv3/oracledb"
    - CACHE_DIR=$HOME/.cache
    - MAVEN_HOME=/usr/local/maven
    - MAVEN_CFG=$HOME/.m2
    - DB_URL="127.0.0.1:1521:XE"
    - DB_USER=app
    - DB_PASS=app
    - ORACLE_VERSION="11g-r2-xe"
    - DOCKER_OPTIONS="--shm-size=1g"
    - UTPLSQL_FILE="utPLSQL"
  matrix:
    - UTPLSQL_VERSION="v3.0.0"
      UTPLSQL_FILE="utPLSQLv3.0.0"
    - UTPLSQL_VERSION="v3.0.1"
    - UTPLSQL_VERSION="v3.0.2"
    - UTPLSQL_VERSION="v3.0.3"
    - UTPLSQL_VERSION="v3.0.4"
    - UTPLSQL_VERSION="v3.1.1"
    - UTPLSQL_VERSION="v3.1.2"
    - UTPLSQL_VERSION="v3.1.3"
    - UTPLSQL_VERSION="v3.1.6"
    - UTPLSQL_VERSION="v3.1.7"
    - UTPLSQL_VERSION="develop"
      UTPLSQL_FILE="utPLSQL"

cache:
  directories:
    - $DOCKER_CFG
    - $CACHE_DIR
    - $MAVEN_CFG

install:
  - bash .travis/maven_cfg.sh
  - bash .travis/start_db.sh
  - bash .travis/install_utplsql.sh
  - bash .travis/install_demo_project.sh

script:
  - mvn package -DskipTests
  - mvn package verify jar:jar appassembler:assemble

before_deploy:
  - bash .travis/create_release.sh
  - if [ ! -z "$TRAVIS_TAG" ]; then VERSION=$(tr -d "/v/" <<<$TRAVIS_TAG); mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=${VERSION}; fi

deploy:
  - provider: releases
    api_key: $GITHUB_API_TOKEN
    file:
      - utPLSQL-cli.zip
      - utPLSQL-cli.zip.md5
    skip_cleanup: true
    on:
      repository: utPLSQL/utPLSQL-cli
      tags: true
      # Use only first job "#xxx.1" to publish artifacts
      condition: "${TRAVIS_JOB_NUMBER} =~ \\.1$"
  - provider: bintray
    file: bintray.json
    user: ${BINTRAY_USER}
    key: ${BINTRAY_API_KEY}
    dry-run: false
    skip_cleanup: true
    on:
      repository: utPLSQL/utPLSQL-cli
      branch: develop
      # Use only first job "#xxx.1" to publish artifacts
      condition: "${TRAVIS_JOB_NUMBER} =~ \\.1$"

notifications:
  slack:
    rooms:
      - secure: "jTPq4AcWQdWp1rB175c05ei/1lXZF1DBoqiKl9PPe7f8vqXS2QLPXMwGTEkZ1YnqL2MPZMB+50Gw5RhLKQ+t+9pN7ejLO0D8ULi1e96PDU5ZL5pNvRglH6U/lR5iT1CjELUuraDXDJ98Vu4gluLMiwTtFYQhNrOoA2V84L+8fF7rGjbGl4/zOXA9RQ4YAcOomJesb4vE7BCjhDjUuMW43xjNWg2s0WAiF+fC1HY/tsBMb1CGfpVULnO5ES5bKtUv/aGtySzH0vXilGDUvhZ/8mdaRn6uxpzcqrFdAyW8elSD28CypcYoxy6Myudw3SFiRPs0/Z02VXvm8DQtU/lcFEnaO7dMG+FpFhsWbrEjcRS6R7ve8uc7e/WuaQhtNVzSTOzRe+JFPGP9FOcYN+AcW2NJFILV9yT7+X/MPIB0OMxuwaPmVgtoyx0oec2nw05azmDr76P2e1XLnKtxa8ouwvPx8EMgApnXSR6VmLGu/w8nmtvIWjEAJ88cdGhwBagtyAsn2frzHq8aKpMziDRYvw4ivwGAeHJFsDtdRXzSbxhxmjl6+is3P0g0iAfojQ/Pzd4GugSYwqRQLLE7dUE0FAKXhKAAQAkjRZxik2+w6jgG8PuLuHdR4pm7C9srL+WAX8aFq/RQXE7BoIdqiZ5TMekw8d6eCRTjcRHsa3pPAd0="
    on_success: change
    on_failure: always
