sudo: required
language: java

services:
  - docker

jdk:
  - oraclejdk8

env:
  global:
    - DOCKER_CFG=$HOME/.docker
    - CACHE_DIR=$HOME/.cache
    - MAVEN_HOME=/usr/local/maven
    - MAVEN_CFG=$HOME/.m2
    - DB_URL="127.0.0.1:1521:XE"
    - DB_USER=app
    - DB_PASS=app
  matrix:
    - ORACLE_VERSION="11g-xe-r2" DOCKER_OPTIONS="--shm-size=1g"

cache:
  directories:
    - $DOCKER_CFG
    - $CACHE_DIR
    - $MAVEN_CFG

install:
  - bash .travis/maven_cfg.sh
  - bash .travis/start_db.sh
  - bash .travis/install_utplsql.sh
  - bash .travis/install_demo_project.sh

script:
  - mvn package -DskipTests
  - mvn package appassembler:assemble

before_deploy:
  - bash .travis/create_release.sh

deploy:
  provider: bintray
  file: bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  dry-run: false
  on: develop
